---
galaxy_info:
  role_name: powervc_create_aixvm
  author: Bhargavaram Akula
  description: Ansible role creates PowerVC VM for Oracle Single Instance Installation
  company: IBM

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
  - name: AIX
    versions:
    - all

  galaxy_tags: [aix]
  dependencies: []

