---
- name: Playbook
  hosts: all
  gather_facts: yes 
  vars_files: vars/oracle_params.yml
  roles:
    - role: preconfig
      tags: preconfig 
    - role: oracle_install
      tags: oracle_install
    - role: oracle_createdb
      tags: oracle_createdb
