---
galaxy_info:
  role_name: oracle_install 
  author: Bhargavaram Akula 
  description: Ansible role performs Oracle Single Database 19c installation on AIX.
  company: IBM

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
  - name: AIX
    versions:
    - all

  galaxy_tags: [aix]
  dependencies: []
