- name: Show which inventory file we are working with.
  ansible.builtin.debug:
    msg: Inventory file is {{ inventory_file }}

- name: Check inventory file for host {{ vm_name }}
  ansible.builtin.command: "grep {{ hostip }} {{ inventory_file }}"
  register: res_ip
  changed_when: res_ip.rc == 1
  failed_when: res_ip.rc > 2

- name: Add VM to the inventory file
  ansible.builtin.lineinfile:
    path: "{{ inventory_file }}"
    line: "{{ vm_name }}  ansible_host={{ hostip }} ansible_ssh_common_args='-o StrictHostKeyChecking=no' ansible_user=root"
  when: res_ip.rc == 1

- name: update known hosts
  ansible.builtin.shell: "ssh-keyscan -H {{ hostip }} >> ~/.ssh/known_hosts"
  when: res_ip.rc == 1

- name: Refresh Inventory
  ansible.builtin.meta: refresh_inventory
