---
# Changing ASM disks ownership and permissions
- name: Change disk {{asm_disk_loc_prefix}}{{item}} ownership
  ansible.builtin.raw: chown {{ora_grid_user}}:{{ora_group}} {{asm_disk_loc_prefix}}{{item}}

- name: Change disk {{asm_disk_loc_prefix}}{{item}} permission
  ansible.builtin.raw: chmod 660 {{asm_disk_loc_prefix}}{{item}}
