# Creating DB on ASM Diskgroup

- name: Templating out Database Template File
  template:
    src: "sn.asm.{{ ora_version }}"
    dest: "{{ files_dir }}/{{ ora_sid }}.dbt"
    owner: "{{  ora_user  }}"
    group: "{{ ora_group }}"
    mode: '0774'

- name: Templating out Database creation script for {{ ora_version }}
  template:
    src: "createdb.19.mfs.ksh"
    dest: "{{ files_dir }}/createdb.19.mfs.ksh"
    owner: "{{ ora_user }}"
    group: "{{ ora_group }}"
    mode: '0744'

- name: Creating the database
  shell: "{{ files_dir }}/createdb.19.mfs.ksh"
  become: yes
  become_method: su
  become_user: "{{ ora_user }}"
