#block:
- name: Creating volume group for the Database
  ibm.power_aix.lvg:
    vg_name: "{{ora_data_vg}}"
    pp_size: 4
    vg_type: scalable
    state: present
    pvs: "{{item}}"
  with_items:  "{{ora_data_vg_disk}}"
  when : ora_data_vg != "rootvg"

- name: Creating {{ora_data_fs}} filesystem
  ibm.power_aix.filesystem:
    filesystem:    "{{ ora_data_fs }}"
    attributes: "size={{ora_data_fs_size}}"
    state: present
    vg: "{{ora_data_vg}}"
    auto_mount: True

- name: Mounting {{ora_data_fs}}
  ibm.power_aix.mount:
    mount_dir:   "{{ ora_data_fs }}"
    state: mount
  ignore_errors: yes

- name: Checking permission of {{ ora_data_fs }}
  ansible.builtin.stat:
    path: "{{ora_data_fs}}"
  register: ora_dir

- name: Changing ownership to {{ ora_user }} on {{ ora_data_fs }}
  ansible.builtin.file:
    path: "{{ ora_data_fs }}"
    state: directory
    recurse: yes
    owner: "{{ ora_user }}"
    group: "{{ ora_group }}"
    mode: '0775'
  when: ora_dir.stat.exists and ora_dir.stat.pw_name != ora_user

- name: Include Create FS Task
  ansible.builtin.include_tasks: crfs.yml
  with_items: "{{ ora_db_fs_list }}"
  loop_control:
    loop_var: item

- name: Templating out Database template file
  ansible.builtin.template:
    src: sn.j2.{{ora_version}}
    dest: "{{ files_dir }}/{{ ora_sid }}.dbt"
    owner: "{{ora_user}}"
    group: "{{ora_group}}"
    mode: '0774'

- name:  Templating out Database creation script for {{ ora_version }}
  ansible.builtin.template:
    src: createdb.19.mfs.ksh
    dest: "{{ files_dir }}/createdb.19.mfs.ksh"
    owner: "{{ ora_user }}"
    group: "{{ ora_group }}"
    mode: '0744'

- name: Creating database
  shell: "{{ files_dir }}/createdb.19.mfs.ksh"
  become: yes
  become_method: su
  become_user: "{{ ora_user }}"

- name: creating and configuring listener
  shell: "{{ ora_home }}/bin/netca -silent -responsefile {{ ora_home }}/assistants/netca/netca.rsp"
  become_method: su
  become: yes
  become_user:  "{{ ora_user }}"  
