---
# Copyright (c) IBM Corporation 2021
# tasks file for oracle database creation via dbca

- name: Set the Oracle Home
  set_fact:
   ora_home: "{{ databases[0].ora_home }}"

- name: Checking /etc/oratab for {{ ora_sid }} existence 
  ansible.builtin.command: "grep {{ ora_sid }} /etc/oratab"
  register: db_check
  failed_when: db_check.rc > 2

- name: Changing permission to {{ora_base}}/admin
  ansible.builtin.file:
    path: "{{ ora_base }}/admin"
    state: directory
    recurse: yes
    owner: "{{ ora_user }}"
    group: "{{ ora_oinstall_group }}"
    mode: '0775'

- name: DB Check
  ansible.builtin.fail:
    msg: "DB {{ora_sid}} is already created"
  when: db_check.stdout | length > 0

- name: DB on ASM Storage
  ansible.builtin.include_tasks: db_asm.yml
  when: grid_asm_flag

- name: Copy disk_validate script
  ansible.builtin.copy:
    src: "../../preconfig/files/disk_validate.sh"
    dest: "{{ scripts_dir }}/disk_validate.sh"
    mode: '0770'

- name: Check Oracle DB VG disks
  ansible.builtin.shell: "{{ scripts_dir }}/disk_validate.sh {{item}} {{ora_data_vg}}"
  loop: "{{ ora_data_vg_disk }}"
  when: not grid_asm_flag

- name: DB on AIX JFS Filesystem
  ansible.builtin.include_tasks: db_jfs.yml
  when: not grid_asm_flag

- name: Check Oracle PMON background process status
  ansible.builtin.shell: "ps -ef|grep ora_pmon_{{ora_sid}}|grep -v grep"
  register: process_check
  failed_when: process_check.rc>1

- name: Create tnsnames.ora 
  ansible.builtin.file:
    path: "{{ ora_home }}/network/admin/tnsnames.ora"
    state: touch
    owner: "{{ ora_user }}"
    group: "{{ ora_oinstall_group }}"

- name: Add TNS Entry to tnsnames.ora
  ansible.builtin.lineinfile:
    path: "{{ ora_home }}/network/admin/tnsnames.ora"
    line: "{{ ora_sid }} = (DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = {{ inventory_hostname }})(PORT = 1521))) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = {{ ora_sid }})))"
  when: process_check.stdout | length > 0

- name: DB check
  block: 
   - ansible.builtin.fail:
       msg: "DB {{ ora_sid }} not is running"
     when: process_check.stdout | length == 0

   - ansible.builtin.debug:
       msg: "DB {{ ora_sid }} is running"
     when: process_check.stdout | length > 0  

- name: Set Database Profile
  ansible.builtin.include_tasks: set_ora_profile.yml
  when: process_check.stdout | length > 0
