---
# Copyright (c) IBM Corporation 2021
# tasks file for oracle database creation via dbca

- name: Checking /etc/oratab for {{ora_sid}} existence 
  command: "grep {{ora_sid}} /etc/oratab"
  register: db_check
  failed_when: db_check.rc > 2


- name: changing permission to {{ora_base}}/admin
  file:
    path: "{{ora_base}}/admin"
    state: directory
    recurse: yes
    owner: "{{ora_user}}"
    group: "{{ora_oinstall_group}}"
    mode: '0775'

- name: DB Check
  fail:
    msg: "DB {{ora_sid}} is already created"
  when: db_check.stdout | length > 0


- name: DB on ASM Storage
  include_tasks: db_asm.yml
  when: grid_asm_flag

- name: Check Oracle DB VG disks
  shell: /tmp/disk_validate.sh {{item}} {{ora_data_vg}}
  loop: "{{ora_data_vg_disk}}"
  when: not grid_asm_flag

- name: DB on AIX JFS Filesystem
  include_tasks: db_jfs.yml
  when: not grid_asm_flag

- name: Check Oracle PMON background process status
  shell: "ps -ef|grep ora_pmon_{{ora_sid}}|grep -v grep"
  register: process_check
  failed_when: process_check.rc>1

- name: Add TNS Entry to tnsnames.ora
  lineinfile:
    path: "{{ora_home}}/network/admin/tnsnames.ora"
    line: "{{ ora_sid }} = (DESCRIPTION = (ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = {{ inventory_hostname }})(PORT = 1521))) (CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = {{ ora_sid }})))"
  when: db_check.stdout | length > 0

- debug:
    var: process_check

- name: DB check
  fail:
    msg: "DB {{ora_sid}} not is running"
  when: process_check.stdout | length == 0

- debug:
    msg: "DB {{ora_sid}} is running"
  when: process_check.stdout | length > 0  
