---
- name: Playbook
  hosts: host118
  gather_facts: yes 
  vars_files: vars/oracle_params_asm_aprf_GoI.yml
  roles:
    - role: preconfig
      tags: preconfig 
    - role: oracle_install_gi
      tags: oracle_install_gi
    - role: oracle_install_db
      tags: oracle_install_db
    - role: oracle_createdb
      tags: oracle_createdb
