- name: Check Disks PVID and VG
  ansible.builtin.shell: "{{ scripts_dir }}/disk_validate.sh {{ item }} 'None'"

- name: Check Disk header
  ansible.builtin.command: lquerypv -h {{ asm_disk_loc_prefix }}{{ item }}
  register: asm_dsk

- ansible.builtin.fail:
    msg: "Disk {{ item }} is old or belong to ASM DG - disk header contains ASM info. If the header information is old, then clear it using the command 'dd if=/dev/zero of=/dev/hdiskX bs=1024k count=100' and retry"
  when: "'ORCLDISK' in asm_dsk.stdout"
