- name: Set fact init_done
  set_fact:
    init_done: true
- name: Set fact scripts dir
  set_fact:
    scripts_dir: "{{ scripts_dir | join('/') }}"

- name: Set fact saved dir
  set_fact:
    saved_dir: "{{ saved_dir | join('/') }}"

- name: Set fact done dir
  set_fact:
    done_dir: "{{ done_dir | join('/') }}"

- name: Set fact files dir
  set_fact:
    files_dir: "{{ files_dir | join('/') }}"

- name: Set fact backup_dir
  set_fact:
    backup_dir: "{{ backup_dir | join('/') }}"

- name: Create work dir
  file:
    path: "{{ work_dir }}"
    state: "directory"
    mode: '0777'

- name: Create scripts dir
  file:
    path: "{{ scripts_dir }}"
    state: "directory"
    mode: '0755'

- name: Create saved dir
  file:
    path: "{{ saved_dir }}"
    state: "directory"
    mode: '0755'

- name: Create done dir
  file:
    path: "{{ done_dir }}"
    state: "directory"
    mode: '0777'

- name: Create files dir
  file:
    path: "{{ files_dir }}"
    state: "directory"
    mode: '0755'

- name: Create backup dir
  file:
    path: "{{ backup_dir }}"
    state: "directory"
    mode: '0777'

