- name: Creating Ansible Work Directories
  file:
    path: "{{ item }}"
    state: "directory"
    mode: '0777'
  with_items:
    - "{{ work_dir }}"
    - "{{ scripts_dir }}"
    - "{{ logs_dir }}"
    - "{{ done_dir }}"
    - "{{ files_dir }}"
    - "{{ backup_dir }}"
